### ISSUE TITLE
无法删除项目

### ISSUE THREAD

**Issue by wind-liang** [xiyuanyuan/just-mock#1]
第一次录屏的时候突然正常了，然后第二次删的时候就又不正常了
如图：
![](https://windliangblog.oss-cn-beijing.aliyuncs.com/windliangblog.oss-cn-beijing.aliyuncs.comKapture%202022-07-21%20at%2009.06.43.gif)

**Comment by 1gehunzi** [comment]
收到，我排查下。欢迎反馈
