### ISSUE TITLE
希望名字都不要限制最小长度

### ISSUE THREAD

**Issue by wind-liang** [xiyuanyuan/just-mock#2]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/13794223/182517044-70cdb581-2690-4116-a8fa-e5abe53ac7a5.png">

<img width="439" alt="image" src="https://user-images.githubusercontent.com/13794223/182517087-0e5e0047-c444-44e0-9697-d0456b66af6e.png">

**Comment by 1gehunzi** [comment]
https://video-1251432287.cos.ap-beijing.myqcloud.com/Just%20Mock-v1.0.1.zip  新插件地址

大佬提的两个bug，我都修了。需要注意：如果重新安装，之前插件配置的规则都会被删除。请谨慎替换😂。

（重新安装，数据丢失问题后续会通过导入，导出文件的形式解决。）
